"""Add role and is_active to User model

Revision ID: 31516416fe8b
Revises: 918675e0646d
Create Date: 2026-06-17 13:38:24.872149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31516416fe8b'
down_revision = '918675e0646d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
