"""Add must_change_password and is_deleted to User

Revision ID: e37b7ae572a3
Revises: 31516416fe8b
Create Date: 2026-06-17 14:53:30.331192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37b7ae572a3'
down_revision = '31516416fe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
