"""Add subscription fields to User

Revision ID: fa790bf40d16
Revises: e37b7ae572a3
Create Date: 2026-06-17 15:10:26.850978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa790bf40d16'
down_revision = 'e37b7ae572a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.String(length=50), server_default='Free', nullable=False))
        batch_op.add_column(sa.Column('monthly_chart_limit', sa.Integer(), server_default='20', nullable=False))
        batch_op.add_column(sa.Column('charts_used_this_month', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('subscription_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_expires_at')
        batch_op.drop_column('subscription_active')
        batch_op.drop_column('charts_used_this_month')
        batch_op.drop_column('monthly_chart_limit')
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###
